apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gpu-pruner
  labels:
    app: gpu-pruner
    release: llmd-kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - fuddin-dev
  selector:
    matchLabels:
      app: gpu-pruner
  endpoints:
    - port: dashboard
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
