resources:
- namespace.yaml
- crs.yaml
- deployment.yaml
- serviceaccount.yaml
- clusterrole.yaml
- service.yaml
- dashboard-service-lb.yaml
- slack-interactions-service-lb.yaml
- servicemonitor.yaml
- weekly-report-script-configmap.yaml
- weekly-report-cronjob.yaml