apiVersion: v1
kind: Secret
metadata:
  name: gpu-pruner-config
  namespace: gpu-pruner-system
type: Opaque
stringData:
  namespace-mentions: |
    {
      "fuddin-": "<@U0B4KPMGEKC>",
      "tessa-": "<@U0B1M4J52F6>",
      "evacchi-": "<@U02KWRTKHH8>",
      "oaplaton-": "<@U0B86NVGGTS>",
      "dpikus-": "<@W4QG1G117>",
      "rsaini-": "<@U03GKH8PEGN>",
      "dolev-": "<@U01JTKK831U>",
      "ecrncevi-": "<@U098265N73R>",
      "kmokhtar-": "<@U0A6WGY3L2W>"
    }
