apiVersion: v1
kind: Secret
metadata:
  name: gpu-pruner-config
  namespace: fuddin-dev
type: Opaque
stringData:
  namespace-mentions: |
    {
      "aasthana-": "<@USER_ID>",
      "acardace-": "<@USER_ID>",
      "algriffi-": "<@USER_ID>",
      "aputtur-": "<@USER_ID>",
      "dagray-": "<@USER_ID>",
      "dolev-": "<@USER_ID>",
      "dpikus-": "<@USER_ID>",
      "ecrncevi-": "<@USER_ID>",
      "effi": "<@USER_ID>",
      "evacchi-": "<@USER_ID>",
      "fuddin-": "<@USER_ID>",
      "grpereir-": "<@USER_ID>",
      "hyarlaga-": "<@USER_ID>",
      "imarkov-": "<@USER_ID>",
      "jmok-": "<@USER_ID>",
      "jochoa-": "<@USER_ID>",
      "klape-": "<@USER_ID>",
      "kmokhtar-": "<@USER_ID>",
      "kpouget-": "<@USER_ID>",
      "kvalin-": "<@USER_ID>",
      "laronovi-": "<@USER_ID>",
      "lmarchal-": "<@USER_ID>",
      "lphiri-": "<@USER_ID>",
      "mambati-": "<@USER_ID>",
      "marcions": "<@USER_ID>",
      "mye": "<@USER_ID>",
      "naisingh-": "<@USER_ID>",
      "inference-": "<@USER_ID",
      "oaplaton-": "<@USER_ID>",
      "otucker-": "<@USER_ID>",
      "pravein": "<@USER_ID>",
      "rajjoshi-": "<@USER_ID>",
      "rbryant-": "<@USER_ID>",
      "rob-": "<@USER_ID>",
      "robshaw-": "<@USER_ID>",
      "rsaini-": "<@USER_ID>",
      "sagmoore-": "<@USER_ID>",
      "sbatsche-": "<@USER_ID>",
      "shuynh-": "<@USER_ID>",
      "tepham-": "<@USER_ID>",
      "tibrahim-": "<@USER_ID>",
      "tysmith-": "<@USER_ID>",
      "vamodi-": "<@USER_ID>",
      "vsuresh-": "<@USER_ID>",
      "weaton-": "<@USER_ID>",
      "wenzhou-": "<@USER_ID>",
      "yzh-": "<@USER_ID>"
    }
