apiVersion: v1
kind: Secret
metadata:
  name: gpu-pruner-config
  namespace: fuddin-dev
type: Opaque
stringData:
  namespace-mentions: |
    {
      "fuddin-": "U0B4KPMGEKC"
      "tessa-": "U0B1M4J52F6"
      
    }
